#!/usr/bin/bash

TEST=test*
SRC=../cppheader.php

for FILE in $TEST
do
   echo "[Processing $FILE]:"
   php -f $SRC -- --input=$FILE | tr -d ' \n\t' > output1
   cat $FILE | tr -d ' \n\t' > output2

   cat output1
   echo ""
   cat output2
   echo ""
   diff output1 output2

   if [ $? == 0 ]
   then
       echo "   $(tput setaf 2)Test successful! $(tput sgr0)"
   else
       echo "   $(tput setaf 1)Test failed!$(tput sgr0)"
   fi
   echo ""
done


